app/models/product.py
import qrcode
from flask import current_app
from app import db
from app.models import BaseModel
from sqlalchemy.orm import relationship
from sqlalchemy import Column, String, Text, ForeignKey, JSON, DateTime, Integer

class Product(BaseModel, db.Model):
    __tablename__ = 'products'
    name = Column(String(25), nullable=False)
    description = Column(Text, nullable=False)

    batches = relationship('Batch', back_populates='product')
    manufacturer_id = Column(String(64), ForeignKey('manufacturers.id'))
    manufacturer = relationship('Manufacturer', back_populates='products')
    
    listings = relationship('Listing', back_populates='product')

    orders = relationship('Order', back_populates='product')

    def generate_qrcode(self):
        """
        Generate QR Code for a product
        """
        data = {
            "product_id": self.id,
            "product_name": self.name,
            "batch_number": self.batch_id,
            "manufacture_date": self.manufacturer_date,
            "expiry_date": self.expiry_date,
            "manufacturer_name": self.manufacturer.fullname,
            "manufacturing_location": self.manufacturer.company_location,
            "checkpoints": [],
            "auth_url": f"{current_app.config['HOST']}/product/verify?product_id={self.id}",
            "digital_signature": "abcd1234efgh5678ijkl"
		}
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        qr.add_data(data)
        qr.make(fit=True)
        img = qr.make_image(fill='black', back_color='white')
        img.save()

    def update_checkpoint(self):
        pass

app/products/__init__.py
from flask import Blueprint

products = Blueprint("products", __name__, url_prefix="/products")

from . import views

app/products/views.py
import json
import csv
import os
from flask import render_template, request, redirect, flash, make_response, url_for, abort
from flask_login import login_required, current_user
from datetime import datetime
from app.models import Product, Batch, db
from flask import current_app
from app.decorators import role_required

from . import products
from werkzeug.utils import secure_filename
from sqlalchemy.exc import IntegrityError


@products.route('/', methods=['POST'])
def add_product():
    print(request.form.to_dict())
    product = Product(
        name=request.form.get('name'),
        description=request.form.get('description'),

        manufacturer_id=current_user.id,
    )
    product.save()
    if not Product.get('id', product.id):
        flash('Error adding product', 'error')
        return redirect(url_for('accounts.dashboard'))
    flash('Product added successfully', 'success')
    return redirect(url_for('accounts.dashboard'))


@products.route("/<product_id>")
@login_required
@role_required('Manufacturer')
def view_product(product_id):
    product = db.session.query(Product).filter_by(id=product_id).first()
    if product:
        return render_template('products/view_product.html', product=product)
    else:
        return make_response({"error": 'Product not found'}), 404


@products.route('/<product_id>/batch/add', methods=['POST'])
def add_batch(product_id):
    product = Product.get('id', product_id)
    if not product:
        flash("Error fetching product")
        return make_response(), 409
    batch = Batch(
        batch_number=request.form.get('batch_number'),
        # qrcode = request.form.get('batch_number'),
        manufacture_date=datetime.strptime(
            request.form.get('manufacture_date'), '%Y-%m-%d'),
        expiry_date=datetime.strptime(
            request.form.get('expiry_date'), '%Y-%m-%d'),
        size=request.form.get('size'),
        measurement=request.form.get('measurement', 'pcs'),

        product_id=product.id,
        product=product
    )
    batch.save()
    if not Batch.get('id', batch.id):
        flash('Error adding batch', 'error')
        return redirect(url_for('products.view_product', product_id=product.id))
    flash('Batch created successfully', 'success')
    return redirect(url_for('products.view_product', product_id=product.id))


@products.route('/<product_id>/batch/upload', methods=['POST'])
def batch_upload(product_id):
    product = Product.get('id', product_id)
    if product is None:
        return make_response({'message': 'Product not found'}), 404
    batches = request.files.get('batch_csv')
    if not batches or not batches.filename.split('.')[1] == 'csv':
        return make_response({'message': 'Invalid file format'}), 400
    TEMP_FOLDER = 'app/static/temp'
    if not os.path.exists(TEMP_FOLDER):
        os.makedirs(TEMP_FOLDER)
    file_path = f'{TEMP_FOLDER}/{secure_filename(batches.filename)}'
    batches.save(file_path)
    if not batches or not batches.filename.split('.')[1] == 'csv':
        abort(400)
    num_saved = 0
    with open(file_path, 'r', newline="") as f:
        values = csv.reader(f)
        total_batches = len(values)
        for value in values:
            try:
                batch = Batch(
                    batch_number=value[0],
                    manufacture_date=datetime.strptime(
                        value[1], '%Y-%m-%d'),
                    expiry_date=datetime.strptime(value[2], '%Y-%m-%d'),
                    size=value[3],
                    measurement=value[4],

                    product_id=product_id,
                    product=product
                )
                batch.save()
                num_saved += 1
            except IndexError:
                pass
            except IntegrityError:
                os.remove(file_path)
                return make_response({'message': 'Failed: Similar batch numbers detected'}), 409
    os.remove(file_path)
    return make_response({'message': f'Added {num_saved} out of {total_batches} batches'}), 201

app/templates/products/add_batch.html
<!-- Add Batch Popup Form -->
<div id="addBatchModal"
	class="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50 overflow-y-scroll hidden">
	<div class="bg-white rounded-lg shadow-lg p-8 max-w-lg w-full relative">
		<button id="closeBatchModal"
			class="absolute top-2 right-5 font-bold text-3xl text-gray-500 hover:text-gray-700">
			&times;
		</button>
		<h2 class="text-2xl font-bold mb-4">Add Batch</h2>
		<h1>Upload a multiple batches in a CSV file</h1>
		<form id="batchUploadForm" action="{{url_for( 'products.batch_upload', product_id=product.id)}}" method="post">
			<input type="hidden" name="_csrf_token" value="{{ csrf_token() }}">
			<div class="h-[300px] w-full m-2 p-2">
				<input type="file" name="batch_csv" id="batch_file" accept="csv">
			</div>
			<div>
				<button class="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded"
					type="submit">Upload
					Batches</button>
			</div>
		</form>
		<details class="mt-2">

			<summary class="font-semibold font-lg cursor-pointer">or Add Manually</summary>
			<form id="addBatchForm" method="post" action="{{ url_for('products.add_batch', product_id=product.id) }}">
				<input type="hidden" name="_csrf_token" value="{{ csrf_token() }}">
				<div class="mb-4">
					<label class="block text-gray-700 text-sm font-bold mb-2" for="batchNumber">Batch Number</label>
					<input
						class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
						id="batchNumber" name="batch_number" type="text" placeholder="Batch Number">
				</div>
				<div class="mb-4">
					<label class="block text-gray-700 text-sm font-bold mb-2" for="manufactureDate">Manufacture
						Date</label>
					<input
						class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
						id="manufactureDate" name="manufacture_date" type="date">
				</div>
				<div class="mb-4">
					<label class="block text-gray-700 text-sm font-bold mb-2" for="expiryDate">Expiry Date</label>
					<input
						class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
						id="expiryDate" name="expiry_date" type="date">
				</div>
				<div class="mb-4">
					<label class="block text-gray-700 text-sm font-bold mb-2" for="batchSize">Batch Size (units)</label>
					<input
						class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
						id="batchSize" name="size" type="number" step="any" placeholder="Batch Size">
				</div>
				<div class="flex items-center justify-between">
					<button id="addBatchSubmit"
						class="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded" type="submit">Add
						Batch</button>
				</div>
			</form>
		</details>
	</div>
</div>
<script>
	document.getElementById('showAddBatchModal').addEventListener('click', function () {
		document.getElementById('addBatchModal').classList.remove('hidden');
	});

	document.getElementById('closeBatchModal').addEventListener('click', function () {
		document.getElementById('addBatchModal').classList.add('hidden');
	});
	document.querySelector('#batchUploadForm').addEventListener('submit', async (event) => {
		event.preventDefault()
		const file = document.querySelector('#batch_file').files[0]
		if (!file) {
			alert('Please select a file to upload')
			return
		}
		const formData = new FormData()
		formData.append('batch_csv', file)
		try {
			const response = await fetch("{{url_for('products.batch_upload', product_id=product.id)}}", {
				method: 'POST',
				body: formData
			})
			if (!response.ok) {
				const error = await response.json()
				throw new Error(error.message)
			}
			alert('Batches uploaded successfully')
		} catch (error) {
			alert(error.message)
		}
	})
	document.getElementById('addBatchSubmit').addEventListener('click', function () {
		// Retrieve form data
		var batchNumber = document.getElementById('batchNumber').value;
		var manufactureDate = document.getElementById('manufactureDate').value;
		var expiryDate = document.getElementById('expiryDate').value;
		var batchSize = document.getElementById('batchSize').value;

		// Create list item for display
		var batchList = document.getElementById('batchList');
		var listItem = document.createElement('li');
		listItem.textContent = `Batch Number: ${batchNumber}, Manufacture Date: ${manufactureDate}, Expiry Date: ${expiryDate}, Size: ${batchSize} units`;
		batchList.appendChild(listItem);

		// Hide modal
		document.getElementById('addBatchModal').classList.add('hidden');

		// Clear form inputs
		document.getElementById('batchNumber').value = '';
		document.getElementById('manufactureDate').value = '';
		document.getElementById('expiryDate').value = '';
		document.getElementById('batchSize').value = '';
	});
</script>

app/templates/products/add_product.html
<!-- Add Product Modal -->
<div id="addProductModal" class="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50 hidden">
    <div class="bg-white rounded-lg shadow-lg p-8 max-w-lg w-full relative">
        <button id="closeModalButton"
            class="absolute top-2 right-5 font-bold text-3xl text-gray-500 hover:text-gray-700">
            &times;
        </button>
        <h2 class="text-2xl font-bold mb-4">Add Product</h2>
        <form id="addProductForm" method="post" action="{{ url_for('products.add_product') }}">
            <input type="hidden" name="_csrf_token" value="{{ csrf_token() }}">
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="productName">Product Name</label>
                <input
                    class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                    id="name" name="name" type="text" placeholder="Product Name" value="">
            </div>
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="productDescription">Description</label>
                <textarea
                    class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                    id="description" name="description" placeholder="Product Description"></textarea>
            </div>
            <div class="flex items-center justify-between">
                <button class="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded" type="submit">Add
                    Product</button>
            </div>
        </form>
    </div>
</div>

<script>
    document.getElementById('addProductButton').addEventListener('click', function () {
        document.getElementById('addProductModal').classList.remove('hidden');
    });

    document.getElementById('closeModalButton').addEventListener('click', function () {
        document.getElementById('addProductModal').classList.add('hidden');
    });
    document.querySelector('#addProductForm').addEventListener('submit', (event) => {
        event.target.reset()
    })
</script>

app/templates/products/view_product.html
{% extends 'base.html' %}
{% block title %}Product{% endblock title %}
{% block content %}
<div class="md:max-w-4xl w-full mx-auto py-8">
    <div class="bg-white shadow-md rounded-lg p-6">
        <h2 class="text-3xl font-semibold mb-4">{{ product.name }}</h2>
        <p class="text-gray-700 mb-6">{{ product.description }}</p>
        <div>
			<div class="w-full mb-8">
				<div class="mt-4 float-right">
					<button id="showAddBatchModal" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Add
						Batch</button>
				</div>
				<h3 class="text-2xl font-semibold mb-2">Available Batches:</h3>
			</div>
            <ul class="flex flex-wrap justify-between divide-y divide-gray-200">
                {% for batch in product.batches %}
                <li class="p-4 m-2 flex bg-gray-200 rounded-md">
                    <div class="flex-1">
                        <div class="flex items-center justify-between">
                            <div class="flex-1">
                                <p class="text-lg font-semibold text-gray-900">Batch Number: {{ batch.batch_number }}</p>
                                <p class="text-sm text-gray-500">Manufacture Date: {{ batch.manufacture_date.strftime('%Y-%m-%d') }}</p>
                                <p class="text-sm text-gray-500">Expiry Date: {{ batch.expiry_date.strftime('%Y-%m-%d') }}</p>
                                <p class="text-sm text-gray-500">Size: {{ batch.size }} unit/s</p>
                            </div>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
		{% include 'products/add_batch.html' %}
    </div>
</div>
{% endblock content %}