app/models/shipment.py
import json
import datetime
from sqlalchemy import Column, String, Integer, Float, DateTime, JSON, ForeignKey
from sqlalchemy.orm import relationship
from app import db
from app.models.base_model import BaseModel


class Shipment(BaseModel, db.Model):
    __tablename__ = 'shipments'
    checkpoints = Column(JSON)
    # Processing, Dispatched, In Transit, Delivered
    destination = Column(String(64), nullable=False)

    orders = relationship('Order', back_populates='shipment',
                          cascade='all, delete-orphan')

    user_id = Column(String(64), ForeignKey('users.id'))
    user = relationship(
        'User', back_populates='shipments', foreign_keys=[user_id])

    def update_checkpoint(self, location, status):
        checkpoints = json.loads(self.checkpoints)
        checkpoints.append({
            'location': location,
            'date': f'{datetime.datetime.now()}',
            'status': status
        })
        self.checkpoints = json.dumps(checkpoints)

    @property
    def get_checkpoints(self):
        return json.loads(self.checkpoints)

    @property
    def status(self):
        return self.get_checkpoints[-1].get('statuus')
    @property
    def current_location(self):
        return self.get_checkpoints[-1].get('location')

app/shipments/__init__.py
from flask import Blueprint

shipments = Blueprint('shipments', __name__)

from . import views

app/shipments/views.py
import json
from datetime import datetime
from app.models import Shipment, Order
from flask import make_response, redirect, url_for, flash, abort, render_template, request
from flask_login import current_user
from app.utils import generate_qr


from . import shipments


@shipments.route('/create', methods=['POST'])
def create_shipment():
    shipment = Shipment(
        destination=request.form.get('destination'),
        checkpoints=json.dumps(
            [
                {
                    'location': request.form.get('current_location'),
                    'date': f'{datetime.now()}',
                    'status': 'Processing'
                }
			]
        ),
        user_id=current_user.id
    )
    shipment.save()
    if Shipment.get('id', shipment.id) is None:
        return make_response({"message": 'Error creating shipment'})
    return redirect(url_for('shipments.view_shipment', shipment_id=shipment.id))


@shipments.route('/<shipment_id>')
def view_shipment(shipment_id):
    shipment = Shipment.get('id', shipment_id)
    if not shipment:
        flash('Shipment not found')
        return redirect(url_for('accounts.dashboard'))
    if shipment.user_id != current_user.id:
        abort(403)
    return render_template('shipments/view_shipment.html', shipment=shipment)


@shipments.route('<shipment_id>/add_order/<order_id>', methods=['POST'])
def add_shipment_order(shipment_id, order_id):
    shipment = Shipment.get('id', shipment_id)
    if not shipment:
        flash('Shipment not found')
        return redirect(url_for('shipments.view_shipment', shipment_id=shipment.id))
    order = Order.get('id', order_id)
    if not order:
        flash('Order not found')
        return redirect(url_for('shipments.view_shipment', shipment_id=shipment.id))
    order.shipment_id = shipment.id
    order.qrcode = generate_qr(order, f'{order.id}.jpg')
    order.save()
    flash('Order added successfully')
    return redirect(url_for('shipments.view_shipment', shipment_id=shipment.id))


@shipments.route('<shipment_id>/dispatch')
def dispatch_shipment(shipment_id):
    shipment = Shipment.get('id', shipment_id)
    if shipment is None:
        flash('Shipment not found')
        return redirect(url_for('accounts.dashboard'))
    shipment.update_checkpoint(
        location=request.form.get('location'),
        status='Dispatched'
	)
    shipment.save()
    flash('Shipment dispatched for shipping')
    return redirect(url_for('accounts.dashboard'))

app/templates/shipments/create_shipment.html
<!-- Add Product Modal -->
<div id="createShipmentModal" class="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50 hidden">
    <div class="bg-white rounded-lg shadow-lg p-8 max-w-lg w-full relative">
        <button id="closeShipmentModal"
            class="absolute top-2 right-5 font-bold text-3xl text-gray-500 hover:text-gray-700">
            &times;
        </button>>
        <h2 class="text-2xl font-bold mb-4">Create Shipment</h2>
        <form id="createShipmentForm" method="post" action="{{ url_for('shipments.create_shipment') }}">
            <input type="hidden" name="_csrf_token" value="{{ csrf_token() }}">
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="current_location">Current Location</label>
                <textarea
                    class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                    id="current_location" name="current_location" placeholder="Current Shipment Location" required>{{current_user.address}}</textarea>
            </div>
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="destination">Destination</label>
                <textarea
                    class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                    id="destination" name="destination" placeholder="Shipment Destination"></textarea>
            </div>
            <div class="flex items-center justify-between">
                <button class="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded" type="submit">Create</button>
            </div>
        </form>
    </div>
</div>

<script>
    document.getElementById('createShipmentButton').addEventListener('click', function () {
        document.getElementById('createShipmentModal').classList.remove('hidden');
    });

    document.getElementById('closeShipmentModal').addEventListener('click', function () {
        document.getElementById('createShipmentModal').classList.add('hidden');
    });

    document.querySelector('#createShipmentForm').addEventListener('submit', function (event) {
		event.target.reset()
    });
</script>

app/templates/shipments/view_shipment.html
{% extends 'base.html' %}
{% block title %}Product{% endblock title %}
{% block content %}
<div class="w-full mx-auto py-8">
	<div class="bg-white shadow-md rounded-lg p-6">
		<h2 class="text-lg font-semibold mb-4">SHPMNT-<strong>{{ shipment.id }}</strong></h2>
		<p class="text-gray-700 mb-6">{{ shipment.description }}</p>
		<div>
			<div class="w-full mb-8">
				<div class="mt-4 float-right">
					<button id="addAlltoShipments"
						class="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">Add
						All</button>
				</div>
				<h3 class="text-2xl font-semibold mb-2">Available Orders:</h3>
			</div>
			<ul class="flex flex-wrap divide-y divide-gray-200">
				{% if current_user.orders_received %}
				{% for order in current_user.orders_received %}
				{% if order not in shipment.orders and not order.shipment %}
				{{order.status}}
				<li class="p-4 m-2 flex bg-gray-200 rounded-md">
					<div class="flex-1">
						<div class="flex items-center justify-between">
							<div class="flex-1">
								<p class="text-lg font-semibold text-gray-900">Order ID: <span id="pending-order-id">{{
										order.id }}</span></p>
								<p class="text-sm text-gray-500">Ordered By: {{ order.recipient.firstname }} {{
									order.recipient.lastname }}</p>
								<h3 class="font-semibold">Contact Details</h3>
								<div class="bg-white p-2 m-2">
									<p class="text-sm text-gray-500">Delivery Address: {{ order.delivery_address }}</p>
									<p class="text-sm text-gray-500">Email Address: {{ order.recipient.email }}</p>
									{% if order.recipient.phone %}
									<p class="text-sm text-gray-500">Delivery Address: {{ order.recipient.phone }}</p>
									{% endif %}
								</div>
								<p class="text-sm text-gray-500">Ordered On: {{ order._created_at }}</p>
								<form
									action="{{url_for('shipments.add_shipment_order', shipment_id=shipment.id, order_id=order.id)}}"
									method="get">
									<div class="flex items-center justify-between mt-2">
										<button id="addShipmentButton"
											class="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded"
											type="submit">Add to Shipment</button>
									</div>
								</form>
							</div>
						</div>
					</div>
				</li>
				{% endif %}
				{% endfor %}
				{% endif %}

			</ul>
			<h3 class="text-2xl font-semibold mb-2">Ready To Ship:</h3>
			<form action="{{url_for('shipments.dispatch_shipment', shipment_id=shipment.id)}}" method="get">
				<div class="flex items-center justify-between mt-2">
					<button id="dispatchShipment"
						class="{% if shipment.status == 'Processing' %}bg-green-600 hover:bg-green-700{% else %} bg-gray-400 {% endif %}
						text-white font-bold py-2 px-4 rounded" type="submit"
						{% if shipment.status != 'Processing' %}disabled{% endif %}>
						{% if shipment.status != 'Processing' and shipment.orders %}{{shipment.status}}{% else %}Dispatch Shipment{% endif %}</button>
				</div>
			</form>
			<ul class="flex flex-wrap divide-y divide-gray-200">
				{% if shipment.orders %}
				{% for order in shipment.orders %}
				<li class="p-4 m-2 flex bg-gray-200 rounded-md">
					<div class="flex-1">
						<div class="flex items-center justify-between">
							<div class="flex-1">
								<p class="text-lg font-semibold text-gray-900">Order ID: {{ order.id }}</p>
								<p class="text-sm text-gray-500">Ordered By: {{ order.recipient.firstname }} {{
									order.recipient.lastname }}</p>
								<h3 class="font-semibold">Contact Details</h3>
								<div class="bg-white p-2 m-2">
									<p class="text-sm text-gray-500">Delivery Address: {{ order.delivery_address }}</p>
									<p class="text-sm text-gray-500">Email Address: {{ order.recipient.email }}</p>
									{% if order.recipient.phone %}
									<p class="text-sm text-gray-500">Delivery Address: {{ order.recipient.phone }}</p>
									{% endif %}
								</div>
								<p class="text-sm text-gray-500">Ordered On: {{ order._created_at }}</p>
							</div>
						</div>
					</div>
				</li>
				{% endfor %}
				{%else%}
				<p>You've not added any orders to this shipping</p>
				{% endif %}
			</ul>
		</div>
		{% include 'shipments/add_shipment_order.html' %}
	</div>
</div>
<script>
	const addAlltoShipments = document.querySelector('#addAlltoShipments')
	const pendingOrderIDs = document.querySelectorAll('#pending-order-id')
	console.log(pendingOrderIDs)
	addAlltoShipments.addEventListener('click', () => {
		pendingOrderIDs.forEach(async (id) => {
			try {
				const response = await fetch(`/shipments/{{shipment.id}}/add_order/${id.textContent}`, {
					method: 'GET',
				})
				if (!response.ok) {
					const errorData = await response.json()
					throw new Error(errorData.message)
				}
				const resp = await response.json()
				window.location.reload()
			} catch (error) {
				alert(error.message)
			}
		});
	})
</script>
{% endblock content %}